export const CEMK_THE_JACKET_VERSION=2;
export const THE_JACKET_BEATS=Object.freeze(["hook","first_fight","meeting_falco","toms_diner","downtime","el_coyote_cojo","ncart_station","megabuilding_h4","abandoned_shanty_town","final_ping","nomad_camp","lizzies_bar","black_car","maria_torres","adam_smasher","test_of_worth","into_the_sunset","flatlined"]);
export const THE_JACKET_PINGS=Object.freeze(["ncart_station","megabuilding_h4","abandoned_shanty_town"]);
const ENDINGS=new Set(["into_the_sunset","flatlined"]);
const FIXED=Object.freeze({hook:["first_fight"],first_fight:["meeting_falco"],meeting_falco:["toms_diner"],toms_diner:["downtime","el_coyote_cojo"],final_ping:["nomad_camp"],nomad_camp:["lizzies_bar","black_car"],lizzies_bar:["maria_torres","adam_smasher","test_of_worth"],black_car:["maria_torres","adam_smasher","test_of_worth"],maria_torres:["into_the_sunset","flatlined"],adam_smasher:["into_the_sunset","flatlined"],test_of_worth:["into_the_sunset","flatlined"]});
const clone=s=>JSON.parse(JSON.stringify(s));
export function createTheJacketState(){return {version:CEMK_THE_JACKET_VERSION,current:"hook",completed:[],completedPings:[],reputation:0,downtimeDays:0,history:[],ending:null};}
export function selectTheJacketHook({hasFixer=false,hasNomad=false}={}){return hasNomad?"nomad":hasFixer?"fixer_no_nomad":"no_fixer_no_nomad";}
export function availableTheJacketBeats(state){validateTheJacketState(state);if(ENDINGS.has(state.current))return [];if(state.current==="downtime"||state.current==="el_coyote_cojo"){const remaining=THE_JACKET_PINGS.filter(p=>!state.completedPings.includes(p));return Object.freeze([...(remaining.length?remaining:["final_ping"]),...(state.current==="downtime"?["el_coyote_cojo"]:[])]);}if(THE_JACKET_PINGS.includes(state.current)){const remaining=THE_JACKET_PINGS.filter(p=>!state.completedPings.includes(p)&&p!==state.current);return Object.freeze(["downtime","el_coyote_cojo",...remaining,...(state.completedPings.length>=2?["final_ping"]:[])]);}return Object.freeze([...(FIXED[state.current]||[])]);}
export function transitionTheJacket(state,next,{actor="player"}={}){validateTheJacketState(state);if(actor!=="player"&&actor!=="rules_engine")throw new Error("STATE_MUTATION_AUTHORITY_DENIED");if(!availableTheJacketBeats(state).includes(next))throw new Error("INVALID_BEAT_TRANSITION");let s=clone(state);if(!s.completed.includes(s.current))s.completed.push(s.current);s.current=next;if(THE_JACKET_PINGS.includes(next)&&!s.completedPings.includes(next)){s.completedPings.push(next);s.reputation=s.completedPings.length===3?2:1;}if(ENDINGS.has(next))s.ending=next;s.history.push({type:"transition",from:state.current,to:next,actor});validateTheJacketState(s);return s;}
export function recordTheJacketPing(state,ping,{actor="player"}={}){validateTheJacketState(state);if(actor!=="player"&&actor!=="rules_engine")throw new Error("STATE_MUTATION_AUTHORITY_DENIED");if(!THE_JACKET_PINGS.includes(ping))throw new Error("UNKNOWN_PING");if(state.completedPings.includes(ping))return clone(state);const s=clone(state);s.completedPings.push(ping);s.reputation=s.completedPings.length===3?2:1;s.history.push({type:"ping",ping});validateTheJacketState(s);return s;}
export function recordTheJacketDowntime(state,days,{actor="player"}={}){validateTheJacketState(state);if(actor!=="player"&&actor!=="rules_engine")throw new Error("STATE_MUTATION_AUTHORITY_DENIED");validateTheJacketState(state);if(!Number.isInteger(days)||days<1||days>3||state.downtimeDays+days>3)throw new Error("DOWNTIME_TOTAL_MAX_3_DAYS");const s=clone(state);s.downtimeDays+=days;s.history.push({type:"downtime",days});return s;}
export function serializeTheJacketState(state){validateTheJacketState(state);return JSON.stringify(state);}
export function loadTheJacketState(raw){const parsed=typeof raw==="string"?JSON.parse(raw):clone(raw);if(parsed.version===1)parsed.version=2;if(parsed.ending===undefined)parsed.ending=ENDINGS.has(parsed.current)?parsed.current:null;validateTheJacketState(parsed);return parsed;}
export function validateTheJacketState(s){if(!s||s.version!==CEMK_THE_JACKET_VERSION)throw new Error("INCOMPATIBLE_THE_JACKET_STATE_VERSION");if(!THE_JACKET_BEATS.includes(s.current))throw new Error("UNKNOWN_CURRENT_BEAT");if(!Array.isArray(s.completed)||!Array.isArray(s.completedPings)||!Array.isArray(s.history))throw new Error("INVALID_THE_JACKET_STATE");if(s.completedPings.some(p=>!THE_JACKET_PINGS.includes(p))||new Set(s.completedPings).size!==s.completedPings.length)throw new Error("INVALID_PING_STATE");const expected=s.completedPings.length===0?0:s.completedPings.length===3?2:1;if(s.reputation!==expected)throw new Error("INVALID_REPUTATION_MILESTONE");if(!Number.isInteger(s.downtimeDays)||s.downtimeDays<0||s.downtimeDays>3)throw new Error("INVALID_DOWNTIME_TOTAL");if(s.ending!==null&&!ENDINGS.has(s.ending))throw new Error("INVALID_ENDING");if(ENDINGS.has(s.current)!==(s.ending!==null)||(s.ending!==null&&s.ending!==s.current))throw new Error("ENDING_STATE_MISMATCH");return true;}
export function theJacketAIContext(state){validateTheJacketState(state);return Object.freeze({adventure:"CEMK_THE_JACKET",version:CEMK_THE_JACKET_VERSION,currentBeat:state.current,availableBeats:[...availableTheJacketBeats(state)],reputation:state.reputation,completedPings:[...state.completedPings],ending:state.ending,authority:Object.freeze({mutateState:false,forceScene:false,decideForPlayer:false,fabricateRoll:false,inventRules:false,revealSealedSecrets:false})});}
