import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {AdventureRuntime,AdventureValidator,AdventureStatus} from '../runtime/adventure_engine_v2.js';

const source=new URL('../modules/red_chrome_cargo.json',import.meta.url);
const redChrome=JSON.parse(fs.readFileSync(source,'utf8'));
const hopeReborn=JSON.parse(fs.readFileSync(new URL('../modules/hope_reborn_campaign.json',import.meta.url),'utf8'));
const angelsShare=JSON.parse(fs.readFileSync(new URL('../modules/hope_reborn_angels_share.json',import.meta.url),'utf8'));
const rng={random:()=>0,int:()=>0};
const known=['SKILL_CHECK','OPPOSED_CHECK','COMBAT_START','COMBAT_RESOLUTION','DAMAGE','REST','TRAVEL','CHASE','NETRUN','NET_ARCHITECTURE','HUMANITY_CHECK','ADDICTION_CHECK','ROLE_ABILITY','PURCHASE','SALE','CYBERWARE_INSTALL','CYBERWARE_REMOVE','REPAIR','CRAFT','MEDICAL','WORLD_TIME_ADVANCE','ITEM_USE'];

function mini(){return {
  id:'v2-mini',schemaVersion:1,contentVersion:1,systemId:'cyberpunk-red',title:'V2 Mini',campaignType:'OFFICIAL_ADVENTURE',
  startDefinition:{startingLocation:'a',startingSceneId:null,initialFlags:{},initialObjectives:['o'],initialNpcIds:[],initialConsequences:[]},
  locations:[{id:'a',name:'A',npcIds:[],encounterIds:[],clueIds:[],secretIds:[],sourceReference:{sourceBook:'T'}},{id:'b',name:'B',npcIds:[],encounterIds:[],clueIds:[],secretIds:[],sourceReference:{sourceBook:'T'}}],
  npcs:[],factions:[],creatures:[],items:[],clues:[],secrets:[],rumors:[],quests:[],scenes:[],encounters:[],triggers:[],conditions:[],consequences:[],clocks:[],timers:[],stateFlags:[],relationships:[],transitions:[],rewards:[],randomTables:[],gmGuidance:[],sourceReferences:[{sourceBook:'T'}],
  objectives:[{id:'o',title:'O',description:'',type:'PRIMARY',prerequisites:[],successConditions:[{type:'FLAG',key:'ready'}],failureConditions:[],consequencesSuccess:[{type:'SET_FLAG',target:'rewarded',value:true}],consequencesFailure:[],sourceReference:{sourceBook:'T'}}],
  events:[
    {id:'only-b',trigger:{type:'ON_DIALOGUE'},prerequisites:[],locationRestrictions:['b'],repeatPolicy:'REPEATABLE',ruleActions:[],consequences:[{type:'ADVANCE_CLOCK',target:'c',value:1}],sourceReference:{sourceBook:'T'}},
    {id:'retry',trigger:{type:'ON_FLAG',target:'try'},prerequisites:[],locationRestrictions:[],repeatPolicy:'UNTIL_SUCCESS',ruleActions:[{id:'check',type:'SKILL_CHECK',required:true}],consequences:[{type:'SET_FLAG',target:'passed',value:true}],sourceReference:{sourceBook:'T'}}
  ],completionConditions:[{type:'OBJECTIVE_COMPLETED',objectiveId:'o'}],failureConditions:[],clocks:[{id:'c',name:'C',current:0,max:5,thresholds:[],sourceReference:{sourceBook:'T'}}]
}}

test('top-level event locationRestrictions are enforced',async()=>{const rt=new AdventureRuntime(mini(),{rng});await rt.start();await rt.processEvent({type:'ON_DIALOGUE'});assert.equal(rt.state.activeClockStates.c.current,0);await rt.enterLocation('b');await rt.processEvent({type:'ON_DIALOGUE'});assert.equal(rt.state.activeClockStates.c.current,1)});
test('REPEATABLE event applies consequences on every valid occurrence',async()=>{const rt=new AdventureRuntime(mini(),{rng});await rt.start();await rt.enterLocation('b');await rt.processEvent({type:'ON_DIALOGUE'});await rt.processEvent({type:'ON_DIALOGUE'});assert.equal(rt.state.activeClockStates.c.current,2)});
test('UNTIL_SUCCESS event is retryable after a blocked rules result',async()=>{let attempts=0;const rulesAdapter={resolve:async action=>{attempts++;return attempts===1?{ok:false,resolved:false,blocked:true,action}:{ok:true,resolved:true,success:true,action}}};const rt=new AdventureRuntime(mini(),{rng,rulesAdapter});await rt.start();let rows=await rt.processEvent({type:'ON_FLAG',flag:'try'});assert.equal(rows[0].blockedByRules,true);assert.equal(rt.state.triggeredEventIds.includes('retry'),false);rows=await rt.processEvent({type:'ON_FLAG',flag:'try'});assert.equal(rows[0].blockedByRules,false);assert.equal(rt.state.flags.passed,true);assert.equal(rt.state.triggeredEventIds.includes('retry'),true)});
test('objective success conditions gate completion and success consequences apply once',async()=>{const rt=new AdventureRuntime(mini(),{rng});await rt.start();let out=await rt.completeObjective('o');assert.equal(out.blocked,true);assert.equal(rt.state.completedObjectiveIds.length,0);rt.state.flags.ready=true;out=await rt.completeObjective('o');assert.equal(out.blocked,false);assert.equal(rt.state.flags.rewarded,true);assert.equal(rt.state.status,AdventureStatus.COMPLETED);await rt.completeObjective('o');assert.equal(rt.state.campaignConsequences.filter(x=>x.target==='rewarded').length,1)});
test('Red Chrome Cargo module validates with Cyberpunk rule actions',()=>{const result=new AdventureValidator({knownRuleActions:known}).validateModule(redChrome);assert.equal(result.ok,true,JSON.stringify(result.errors));assert.equal(redChrome.startDefinition.startingLocation,'rcc_hornet_train');assert.ok(redChrome.locations.length>=6);assert.ok(redChrome.events.length>=6);assert.ok(redChrome.encounters.length>=2)});
test('Red Chrome Cargo starts deterministically and keeps sealed cargo secret hidden',async()=>{const rt=new AdventureRuntime(redChrome,{rng});await rt.start();assert.equal(rt.state.currentLocationId,'rcc_hornet_train');assert.equal(rt.state.currentSceneId,'rcc_scene_briefing');const ctx=rt.buildAiContext();assert.equal(ctx.playerKnowledge.revealedSecretIds.includes('rcc_secret_cargo'),false);assert.ok(ctx.gmKnowledge.unrevealedSecrets.some(x=>x.id==='rcc_secret_cargo'))});

test('Hope Reborn campaign spine validates and starts at the Forlorn Hope',async()=>{const result=new AdventureValidator({knownRuleActions:known}).validateModule(hopeReborn);assert.equal(result.ok,true,JSON.stringify(result.errors));const rt=new AdventureRuntime(hopeReborn,{rng});await rt.start();assert.equal(rt.state.currentLocationId,'hr_forlorn_hope');assert.equal(rt.state.currentSceneId,'hr_scene_campaign_open');assert.equal(rt.state.flags.hr_current_mission,'angels_share');assert.equal(rt.state.status,AdventureStatus.ACTIVE)});
test('Hope Reborn campaign mission order is deterministic and event-driven',async()=>{const rt=new AdventureRuntime(hopeReborn,{rng});await rt.start();const sequence=[['hr_mission_angels_share_complete','real_estate_rumble'],['hr_mission_real_estate_rumble_complete','welcome_to_the_neighborhood'],['hr_mission_welcome_to_the_neighborhood_complete','devils_cut'],['hr_mission_devils_cut_complete','hopes_calling'],['hr_mission_hopes_calling_complete','ripping_the_ripper']];for(const [flag,next] of sequence){rt.state.flags[flag]=true;await rt.processEvent({type:'ON_FLAG',flag});assert.equal(rt.state.flags.hr_current_mission,next)}});
test('Hope Reborn campaign does not falsely complete before final mission state',async()=>{const rt=new AdventureRuntime(hopeReborn,{rng});await rt.start();assert.equal(rt.evaluateCompletion(),AdventureStatus.ACTIVE);rt.state.flags.hr_mission_ripping_the_ripper_complete=true;await rt.completeObjective('hr_obj_campaign');assert.equal(rt.evaluateCompletion(),AdventureStatus.COMPLETED)});

test("Angel's Share validates as a full deterministic Beat graph",()=>{const result=new AdventureValidator({knownRuleActions:known}).validateModule(angelsShare);assert.equal(result.ok,true,JSON.stringify(result.errors));assert.equal(angelsShare.startDefinition.startingLocation,'as_forlorn_hope');assert.ok(angelsShare.scenes.length>=14);assert.ok(angelsShare.locations.length>=5);assert.ok(angelsShare.events.length>=7);assert.ok(angelsShare.encounters.length>=3)});
test("Angel's Share opening keeps the later Hope disaster sealed",async()=>{const rt=new AdventureRuntime(angelsShare,{rng});await rt.start();const ctx=rt.buildAiContext();assert.equal(rt.state.currentSceneId,'as_scene_hook');assert.equal(ctx.playerKnowledge.revealedSecretIds.includes('as_secret_tragic_night'),false);assert.ok(ctx.gmKnowledge.unrevealedSecrets.some(x=>x.id==='as_secret_tragic_night'))});
test("Angel's Share investigation does not force the Chrome Cross branch",async()=>{const rt=new AdventureRuntime(angelsShare,{rng});await rt.start();rt.state.flags.as_job_accepted=true;await rt.processEvent({type:'ON_FLAG',flag:'as_job_accepted'});assert.equal(rt.state.currentSceneId,'as_scene_blankety_blank');assert.ok(angelsShare.scenes.find(x=>x.id==='as_scene_blankety_blank').exits.includes('as_scene_chrome_cross'));assert.ok(angelsShare.scenes.find(x=>x.id==='as_scene_blankety_blank').exits.includes('as_scene_blank_hq'));assert.equal(rt.state.currentLocationId,'as_forlorn_hope')});
test("Angel's Share crisis reveal is state-gated and advances the crisis clock",async()=>{const rt=new AdventureRuntime(angelsShare,{rng});await rt.start();assert.equal(rt.revealSecret('as_secret_tragic_night').blocked,true);await rt.enterLocation('as_hope_disaster');assert.equal(rt.state.flags.as_crisis_started,true);assert.equal(rt.state.activeClockStates.as_clock_crisis.current,1);assert.equal(rt.revealSecret('as_secret_tragic_night').revealed,true)});
test("Angel's Share rescue Beat list remains optional and converges without auto-running hazards",async()=>{const rt=new AdventureRuntime(angelsShare,{rng});await rt.start();await rt.enterLocation('as_hope_disaster');const rescue=angelsShare.scenes.find(x=>x.id==='as_scene_search_rescue');const hazards=['as_scene_bar_area','as_scene_electrified_stage','as_scene_locked_freezer','as_scene_storage_room','as_scene_spreading_fire'];for(const id of hazards)assert.ok(rescue.exits.includes(id));assert.equal(rt.state.triggeredEventIds.some(id=>id.includes('bar_area')||id.includes('electrified')||id.includes('freezer')),false)});
test("Angel's Share climax preserves the player's fight-or-leave choice",async()=>{const rt=new AdventureRuntime(angelsShare,{rng});await rt.start();await rt.enterLocation('as_hope_disaster');rt.state.flags.as_rescue_regrouped=true;await rt.processEvent({type:'ON_FLAG',flag:'as_rescue_regrouped'});assert.equal(rt.state.currentSceneId,'as_scene_pickup_game');const scene=angelsShare.scenes.find(x=>x.id==='as_scene_pickup_game');assert.ok(scene.knownFacts.some(x=>/stay and fight|fight or leave|choice is theirs/i.test(x)));assert.equal(rt.state.flags.as_climax_resolved,undefined)});
test("Angel's Share resolution emits the Hope Reborn campaign handoff flag",async()=>{const rt=new AdventureRuntime(angelsShare,{rng});await rt.start();await rt.enterLocation('as_from_the_ashes');assert.equal(rt.state.flags.as_resolution_reached,true);assert.equal(rt.state.flags.hr_mission_angels_share_complete,true);await rt.completeObjective('as_obj_survive_night');assert.equal(rt.state.status,AdventureStatus.COMPLETED)});